### ISSUE TITLE
Pictograms: no lag time & inform user actively when pics are finished loading

### ISSUE THREAD

**Issue by ms-mialingvo** [asterics/AsTeRICS-Grid#715]
When using a grid set on a device for the first time it loads/caches all pictures of one grid as you open that specific grid for the first time. When clicking again, the pictures are already loaded.
When using a grid set with several dozens of grids, this makes it impossible to use the grid set offline before you have clicked on each single grid which takes a long time depending on the amount of grids plus it's hard to keep track which grid is already loaded.
Is there any way around this, a way to force the loading of all pictures at once?

**Comment by klues** [comment]
Actually background loading is already happening. After importing a set, there is this loading icon at the left bottom:

<img width="601" height="351" alt="Image" src="https://github.com/user-attachments/assets/5da7f076-f189-4006-ae5a-368230fb48b2" />

This is indicating that images are loading in the background. After it's gone all images should be cached and everything should be usable offline. Just tested - for me on Windows/Chrome it works.

**Comment by ms-mialingvo** [comment]
Okay, so then when wanting to use a big grid like say Quick Core 112, it takes literally several minutes (have been waiting for 10 minutes now and it's still syncing) until it sync is finished. The user needs to be aware that they need to wait for all that time until they can use the grid without issues and that while they are on the grid the syncing is not working. So, when activating the grid set there should be some message informing the user of that.

**Comment by ms-mialingvo** [comment]
Also, even then there is the delay.
Video 1 shows a grid set after fully finishing sync and going offline. It takes up to 18 seconds, see 1:08 for one grid to load, making AG unusable for communication. https://we.tl/t-GlQGoLc2Zj 
Vdeo 2 shows the same grid set, still offline. Even after pictograms have loaded once, sometimes after waiting enough time or switching to other sites it has to reload the images again, taking again time. So far it feels random if grids reload or remember the images. https://we.tl/t-KmqMzSgRYd
I can't test it on 667 as the 'manage grids' is stuck there.

**Comment by klues** [comment]
Thanks, I could reproduce it on Windows/Chrome. I have to check what happens and why automatic image caching doesn't work. After one page was fully loaded, it loads fast afterwards - so here caching seems to work.

**Comment by ms-mialingvo** [comment]
> Okay, so then when wanting to use a big grid like say Quick Core 112, it takes literally several minutes (have been waiting for 10 minutes now and it's still syncing) until it sync is finished. The user needs to be aware that they need to wait for all that time until they can use the grid without issues and that while they are on the grid the syncing is not working. So, when activating the grid set there should be some message informing the user of that.

or like just have the user wait until the board is actually ready like weavechatconnection (browser) does. Also I don't know what method they use but they have zero lag in images appearing when navigating, online and offline. Literally even just a lag of 1 second will not allow users to get fast through motor automatization like here https://youtu.be/AFt-NT5wsDQ?si=is0iCD2eSXqrAUEU&t=107

https://github.com/user-attachments/assets/8afea9ff-7e8c-4d61-92e5-6c7f9d79156f

**Comment by klues** [comment]
This turned out to be more work than expected, but I think it's quite good now:
* caching should now work more reliable
* after importing a gridset, there is a notification at the bottom showing the progess of downloading the images
* if app is closed/reloaded while downloading, it just continues (but starts at `0%` again, which is related to the actually remaining images)
* in the process I improved the generation of the thumbnails (for `Manage grids` view), because it's related, they now have better quality and work more reliably

Please test at https://gridbeta-github.asterics-foundation.org/klues/715-pictogram-caching-improvements/pr
@arasaac-dga please also test.
Info: we aware that maybe opening this beta for the first time will start to cache many images, because it will try to cache all images you have ever imported in any of these beta-versions (also from other issues). This is the first beta version actually having enabled the caching and therefore it will try to cache everything from previous tests. You can test in browsers "private" mode to prevent this.

**Comment by arasaac-dga** [comment]
Tested and working althoung only with a offline user because from the testing URL we cannnot connect online users (give an net error). The only issue we've encountered is that while the download progress window was displayed, a new window appeared reminding us to create a backup. When this window closed, the image download progress window disappeared, so we lost the reference point (we still see the spinning wheel as before).

We understand it will work the same way with online users, although, as mentioned, we haven't been able to test it because we can't connect them.

**Comment by klues** [comment]
Thanks for testing!

>  althoung only with a offline user because from the testing URL we cannnot connect online users

no problem - this part isn't related to online users - so it will be the same for them.

> this window closed, the image download progress window disappeared, so we lost the reference point

okay - I think this is a quite rare case and you're still seeing the spinning wheel. If you just reload/reopen the app in this case the notification about the caching progress is shown again. So I think it's a minor thing we could leave as-is for now.

**Comment by arasaac-dga** [comment]
> okay - I think this is a quite rare case and you're still seeing the spinning wheel. If you just reload/reopen the app in this case the notification about the caching progress is shown again. So I think it's a minor thing we could leave as-is for now.

ok, no problem

**Comment by ms-mialingvo** [comment]
Thanks, I'll only manage to test it in the weekend.

**Comment by ms-mialingvo** [comment]
Tested in iOS

>  You can test in browsers "private" mode to prevent this.

(On firefox private mode clicking on 'use asterics grid without registration' it just keeps spinning. Not sure since when that is. On the second attempt it even just got stuck on a blank page with the spinning icon without even showing the starting page anymore. Strange. I think I've had issues in the past too but don't usually use private mode so it hasn't been important. Plus Firefox is not working well for other reasons either currently.)

Chrome and Safari are way faster than Firefox (iOS), like 15min vs like 4minutes for Core 84. Any idea why? (Just curious - since Firefox isn't currently working for AG properly it's not that relevant.)

Overall waaay better. :) Still some small glitches and a bit slow reactions here and there (see video, Chrome) but I get the impression that those improve with use. It's also working offline too 👍 

https://github.com/user-attachments/assets/a102470e-d570-42f6-9c73-79fbae293e94

**Comment by ms-mialingvo** [comment]
Btw I just tested Coughdrop on browser (Chrome) to compare and also see if it has the #753 issue too. It doesn't have the #753 problem since it doesn't have a proper fullscreen mode, but when navigating it does load with zero lag once the site has loaded once so I feel like there is still space for improvement for Asterics Grid too?

https://github.com/user-attachments/assets/4d44eea3-cc69-4a15-a570-b123f54d5ba8

**Comment by klues** [comment]
Thanks for testing!

> On firefox private mode clicking on 'use asterics grid without registration' it just keeps spinning. Not sure since when that is.

Could not reproduce on Windows, but fixed a bug in Firefox regarding screenshot generation. So maybe it now also works on iOS?!

> Chrome and Safari are way faster than Firefox (iOS), like 15min vs like 4minutes for Core 84. Any idea why?

It seems like Firefox isn't so optimized in handling that many cache requests (over `3000` in that case). I've now tried to change the logic so that always `10` images are cached in parallel instead of doing one after another. Seems like it sped up things quite much in both Firefox and Chrome for me - please test: https://gridbeta-github.asterics-foundation.org/klues/715-pictogram-caching-improvements/pr

> so I feel like there is still space for improvement for Asterics Grid too?

yes, I would have to look how they're doing it. I think it has to do with global grid and having the possibility of completely dynamic grid sizes. So I'm calculating the resulting grid at each navigation while if I have a fixed grid size for all grids in the current config it's much easier to just swap texts and images (with much less lag). But it's another issue - feel free to open one for it.

**Comment by ms-mialingvo** [comment]
Thanks!

iOS: Firefox, Chrome, Safari - now all working very well, online and offline. Basically zero lag, yay :) Veeeeeeeery minor observation: In firefox it moves super fast through the percentage and then gets stuck for quite a while on a single number. 

Windows, Edge: See video, tested only online, this is after all images supposedly were downloaded
https://github.com/user-attachments/assets/713878e0-f1ed-4eef-a840-49de69f2a35c

Android, Chrome: See video, tested only online, this is after all images supposedly were downloaded
https://github.com/user-attachments/assets/0380933d-49c8-4878-ae37-2c68c0dd8551

Android, Firefox: See video, tested only online, this is after all images supposedly were downloaded
https://github.com/user-attachments/assets/e3de7e17-200f-4d63-b3e6-96329466229d

@arasaac-dga Did things get worse with the second update? Or was it working at the same level when you tested on Android?

@klues this seems to be a more complex thing. 🫣 I suggest doing https://github.com/asterics/AsTeRICS-Grid/pull/670 and https://github.com/asterics/AsTeRICS-Grid/pull/710 first as I assume that those 2 are pretty much finished.

**Comment by ms-mialingvo** [comment]
(Also tested CoughDrop on Windows Edge for comparison and it's similar as for iOS: It takes a moment for a site to load the very first time, afterwards it's nearly as fast as on iOS (about 0.5 seconds wait for site change). So yeah, it might be worth checking what they (and weavechat) are doing.)

**Comment by arasaac-dga** [comment]
> [@arasaac-dga](https://github.com/arasaac-dga) Did things get worse with the second update? Or was it working at the same level when you tested on Android?

We only tested the download progress bar but don't make perfomance testing on Android Tablets because nowadays we have no modern tablet to test it. Only an old one in which Asterics goes very very slow. We have tested in a Samsumg Galaxy S24 over Chrome and there is no lag. It charges and show all the pictograms downloaded very fast between grids. But we think that is not representative because is a powerful device.

**Comment by klues** [comment]
Did some more improvements:
* fixed non-working images in collect element offline (found out by chance)
* performance:
   * found out that probably the biggest issue regarding performance on navigating was the automatic creation of the screenshot/thumbnail
   * changed the logic for creating the thumbnails, now I manually track for which grids we need to do create thumbnails, before I did some hashing which seemed to be not performant and not reliable.

In my tests performance while navigating is much better now, both on Windows and on Android. Did not test on iOS. The strange lag when clicking on an element before the actual navigation is done seems to be gone.

Please test at https://gridbeta-github.asterics-foundation.org/klues/715-pictogram-caching-improvements/pr
Please also test creation/updating on thumbnails (shown in Manage grids) after updating a grid.
After opening the link you have to wait for the update notification and update - like in the main version.

**Comment by klues** [comment]
Oh man, did some tests on my own, all with Quick Core 84.

Windows:
* Chrome: works okay, no instant page transitions, but <1s
* Firefox: sometimes some lag <1s, after some navigating around also sometimes no lag at all
* Edge: same as Chrome, but only in private mode, if in normal mode very slow - I don't know why. After clearing all page data fast again in normal mode...

Android:
* Chrome: downloading images takes very long, page transitions sometimes very slow, sometimes very fast. I don't understand it.

**Comment by arasaac-dga** [comment]
In our case, testing with ARASAAC Comunicador Global Grid Core very bad experience on Edge and Chrome on Widows. Big delays in charge the images on boards each time you load a board and every time you do it. Seem not caching the images. Initial loading charge very slow too.

**Comment by klues** [comment]
So, after like 1 million tries and tests I think it's working quite well now.

Tested mainly "Quick Core 84", but also ARASAAC sets and AsTeRICS Grid default:
* Win11, Chrome and Edge - I think works quite well, fast at downloading images, not really any lag at navigating
* Win11, Firefox: slower at downloading for any Firefox-internal reason, a littlebit lag at navigating, but cannot really say if it's better or worse than the current main version?!
* Android 15, Chrome: good download speed, little lag, again difficult to compare with current main version
* iPad Pro, iOS 18.5, Safari: very good, seems like no lag at all at navigating

Didn't think that this could become so difficult. However also improved many things under the hood, so in total caching images (and also the app for offline use) should hopefully be much more stable now.

Please test at https://gridbeta-github.asterics-foundation.org/klues/715-pictogram-caching-improvements/pr

**Comment by arasaac-dga** [comment]
Wowwww!!! Much much better. Fast as expected. Tested on W10 on Edge, Chrome and Firtefox. A minum delay on Firefox as first time you charge a grid but after that very fast without delays.

**Comment by klues** [comment]
one last update: I also tried to update the library in the background which is used for caching ([Workbox](https://developer.chrome.com/docs/workbox) from version `5.1.2` to `7.4.0`) and in the version from yesterday there was still an error with `7.4.0` and so I decided to keep the old version. Now I fixed the error and we're using the current version `7.4.0`.

Functionality should be the same as yesterday, but with the new library version in the background (which hopefully improved also some things - it should be better to use the current versions of libraries).

Finally hopefully this is done and ready for release.

**Comment by klues** [comment]
also tested transitions from old version to new version locally now:
* cache images with old version (same as current main)
* update to new version
* everything still works offline (without re-caching all images, but using existing images in cache)
* tested on Win11, Chrome, Edge, Firefox

@ms-mialingvo maybe you could also do some tests again, then I think we should be ready for release.

**Comment by ms-mialingvo** [comment]
Yes, I'll test this afternoon :)

**Comment by ms-mialingvo** [comment]
Alright. Tested primarily with Quick Core 84.

iOS, Firefox: It was working quite fast when I last tested, except for #753, now it's fully broken. 😅 Picture loading bar is stuck at 0%. When typing just the error-image appears. If #753 can't be fixed, it's however obsolete because that would mean Asterics can't be used in Firefox iOS.

<img width="770" height="568" alt="Image" src="https://github.com/user-attachments/assets/ea5a2e14-c71f-4de9-a820-ed6cc666b3e7" />


iOS, Chrome: This is where it works absolutely best, from all plattforms and browsers I tested!!! I don't know why it's different but if it could be like this everywhere that would be quite optimal. I mean images reload still but they do it very fast. Only minor thing (applies everyhere but very well visible here): It seems that the first section of this comment was not implemented? https://github.com/asterics/AsTeRICS-Grid/issues/228#issuecomment-3685607557 

iOS, Safari: When navigating and reappearing, the images are the error image first. I'm pretty sure this was not happening earlier. Also, it stayed for 1:05 minutes at 0% (while the sync arrows were moving) which made me think first it was broken but then it did load with no further issues.

Windows, Chrome: sometimes images appear immediately, sometimes they reload. Way faster than earlier, though. :)

Android, Firefox and Chrome: First load can take up to 3 seconds, navigation like 1 second. So, better but still enough slow to be annoying, when one is used to the zero lag of non-web apps. Also tested Firefox with global grid deactivated, not much of a difference. Also compared with coughdrop and weavechat. (Weavechat is fastest (really zero lag) in all browsers/systems but it doesn't work offline so must have some fully different system...)

In all tests, offline versions were working similar to online versions.

For testing comparison: I'm always deleting and reinstalling browsers (I could reset settings but that's more complicated) and then setting a desktop bookmark/"install" and testing from there, as that's the way people will usually use it.

Videos of the various tests: https://we.tl/t-qKmH7pyhL4

**Comment by klues** [comment]
Thanks so much for testing! :)
And: oh, no - I cannot believe that it's still not working in some combinations. Feels like random try & error... :/

> iOS, Firefox:

Which iOS / Firefox versions?
Seems like this combination is used so rarely, that even browserstack.com which I use for testing sometimes does not have it.
But I'll try for myself with our devices (iOS 18 and 13), which I currently do not have here - I'll also try #753 then.

> Android, Firefox and Chrome: First load can take up to 3 seconds, navigation like 1 second. 

"first load" is the caching of the images or first load of a grid? And loading after the image caching in the background is finished or while it's still caching?

> Also compared with coughdrop and weavechat. 

Unfortunately both not open source, so I cannot look what they are doing. However, just found https://github.com/open-aac/sweet-suite-aac - which seems to be a quite recent fork of CoughDrop.

> It seems that the first section of this comment was not implemented? https://github.com/asterics/AsTeRICS-Grid/issues/228#issuecomment-3685607557

No - but I won't start to do it within this issue, because it already has so much changes and this would be an even new field for making changes and testing. So the goal is to get the current state stable.

**Comment by klues** [comment]
> For testing comparison: I'm always deleting and reinstalling browsers (I could reset settings but that's more complicated) and then setting a desktop bookmark/"install" and testing from there, as that's the way people will usually use it.

ok, I always just used private mode / new private tabs, also should give a "clean" setup for each test and should be much less effort.

**Comment by ms-mialingvo** [comment]
> Which iOS / Firefox versions?

iOS 18.5, Firefox 147.5

> "first load" is the caching of the images or first load of a grid? And loading after the image caching in the background is finished or while it's still caching?

Accessing a specific page for the first time after image caching supposedly is finished - it's not for all pages, though, some are randomly faster some slower. After that first load it's all somewhat faster. I haven't experimented in any system with things like putting the device to sleep mode or shutting it down to see how it behaves afterwards, if it still "remembers" or acts again like it was the first time.

> ok, I always just used private mode / new private tabs, also should give a "clean" setup for each test and should be much less effort.

Yeah, given that AG doesn't always work for me in private mode and that there is a difference between the browser and the "installed" version (like in Firefox iOS full screen not working in the browser, however working fine in the installed version) I do that to make sure it works in the setup that the user is most likely to use. Only when it comes to bigger changes like this one, not for small ones.

**Comment by klues** [comment]
Did these things:
* app now shows message that offline mode is not supported by browser, if this is the case. No stuck at `0%` downloading messages anymore
* broken offline mode on iOS `13` works again

Tested now mainly `Global core communicator ARASAAC`, both on new and main version:

* iPad Air 2, iOS 13.2.3
   * Firefox: caching not working in general, `new` shows message that browser doesn't support it (see above)
   * Safari: works with some lag at navigation, `new` feels slightly faster than `main`
* iPad Pro, 12,9 inch, 3rd gen, iOS 18.5
   * Firefox: both working, both very fast, no real difference
   * Safari:
      * both working, both very fast, no real difference
      * also tested with `Quick core 84` - also very fast  
* Windows 11
   * Edge: both working, both very fast, no real difference
   * Chrome: both working, both very fast, no real difference
   * Firefox: first time loading of grids not instant, you see images appearing. `new` sometimes a little bit slower?!
* Android 15
   * Firefox: no instant first navigation, but quite fast, no difference between `new` and `main`
   * Chrome: in both versions not instant, but quite fast, no real difference
* Android 12
   *  Chrome: some lag, but `new` feels faster

So in total only on Win11, Firefox it seems that the `new` version is somehow slower for any reason, on Android 12 `new` seems faster. Otherwise not much differences. A littlebit frustrating after all the work, however now at least in the background many things have improved, and downloading images is in general faster and more stable (and with user feedback).

The reason why I've mainly not tested the `Quick core` sets now is that the image API used in these sets is wrongly configured, which limits caching possibilities of it. That's the reason why caching doesn't works as it should - it works now, offline is now possible, but often with big lags. I think I know the internal reason for it, but I cannot fix the image API that is used in these sets... Therefore for these `Quick core` sets it may now seem like `main` is working better than `new`, but at `main` auto-caching didn't work at all and if you open all grids manually on your own caching works better and then also faster... It's complicated and complicated to explain :/

@ms-mialingvo please test again the cases where you had problems in your last test, if possible. I really hope then this issue is finished.

**Comment by klues** [comment]
@ms-mialingvo I have a new idea to improve things which I want to try, so actually no need for testing right now, sorry.

**Comment by klues** [comment]
Yeah, I think I finally did it! 🥳 

After many discussions with AI which seemingly often gave me way to complex and confusing solutions, I finally implemented the easy solution where thought it should work - and it seems like it is the case! 😀 

So finally also `Quick core 84` works quite fast on my Android 15, Chrome. Android 15, Firefox still more lag, but not that very, very long lag as before. Also quickly tested Win11, Edge and Firefox and Chrome - where everything works fine as before. iOS 18.5, Firefox and Safari also fine.

iOS 13, Safari - the images aren't showing up in the collect element, so one final thing to fix, but otherwise I think it's fine now.

**Comment by klues** [comment]
> iOS 13, Safari - the images aren't showing up in the collect element, so one final thing to fix, but otherwise I think it's fine now.

works now, so I think everything fine now 😎 🥳

**Comment by ms-mialingvo** [comment]
Overall: It loads with 1 second or less accross all browsers and systems I tested! 🥳🥳🥳 Slowest is Firefox Android where the navigation is slow. But overall so much better 🥳

It's so interesting how it varies accross browsers and systems, sometimes it's the navigation + images appearing that takes a moment, sometimes it's only the images appearing. One issue that would be great to solve is how it's working for iOS though. The "error-questionmark" images are still appearing. They weren't about 1.5 week ago when I tested there. I find that quite distracting because it's first the error-images taking a moment to load and then it changing to the real images. And since this wasn't happening earlier I assume it can be fixed.

(Video showing this + also I don't know if you can do anything with that info but the error-pictures make it clearer that some pics don't reload and others do and it's different accross browsers, like e.g. in one browser the home pic is not reloading in another the back pic..)

https://github.com/user-attachments/assets/a492576b-df16-487a-947b-e2f676319cd6

> app now shows message that offline mode is not supported by browser, if this is the case.

It's kind of a different topic but the main problem with Firefox on iOS is not the working offline (well, the iPad I'm testing on is too new to see that error at least) but the #753 message which is independent of online/offline. So there should be a message for that. 

PS: Due to some error on Chrome (761) I compared with the nonbeta version and at least on iOS it seems a bit of a trade-off has happened, it was smoother earlier once it hat loaded for the first time (I had already loaded 'me' and 'do'). (Video from Safari)

https://github.com/user-attachments/assets/0d61b84c-f131-435b-8591-004da2359d26

**Comment by klues** [comment]
Thanks for being so patient and steady in testing! 👏 👍 

> The "error-questionmark" images are still appearing. They weren't about 1.5 week ago when I tested there.

Should be fixed. The reason was that in the background the image was loaded 2 times in some cases - the first failed and the second succeeded - for some internal caching-related reason. Now the first try succeeds and no questionmark anymore. Should also have improved performance.

>  I compared with the nonbeta version and at least on iOS it seems a bit of a trade-off has happened, it was smoother earlier once it hat loaded for the first time

Maybe now also better with the new fix.
I've now tested again at iOS 13 (Safari), iOS 18 (Safari, Firefox), Android (Firefox - now seems also be faster after first load?!) and Win 11 (Chrome, Firefox).

So again - I hope now we're ready for release 😆

**Comment by klues** [comment]
I've now merged the PR and released the current state to https://grid.asterics.eu/latest/ - which is one step closer to the main version, because you can use the same users you have in main version there.

**Comment by arasaac-dga** [comment]
In a quick test, in Chrome W10 the bubble with download % only are shown when arrive 100% (when all the images are cached). Not show the progress as made for example in Edge. In Edge the download progrees works as expected.

About lags on W10: almost perfect onChrome and Edge. Little lag on Firefox but much better than before.

**Comment by klues** [comment]
> In a quick test, in Chrome W10 the bubble with download % only are shown when arrive 100%

Probably because all images are already cached and so it directly or very quickly goes to 100%.

**Comment by arasaac-dga** [comment]
No I have tested with several accounts and new account and meanwhile in the cloud next to the username the spinner is round there is no bubble with download progress. But when spinner inside cloud stop the the bubble appear showing 100%.

**Comment by klues** [comment]
Yes, the spinner within the cloud means: data is synchronization from database (grids) to client. The spinner without the cloud means: downloading (pre-caching) images. Pre-caching of images only starts after the sync with database was completed.

**Comment by arasaac-dga** [comment]
Ahhh ok. Then perhaps in Chrome goes extremely fast caching ;-)

**Comment by ms-mialingvo** [comment]
Questionmark was fixed on iOS and there is basically zero lag now there, so it's currently the smoothest system. Android and Windows are a bit slower for navigation, around 1 second, but overall a huge improvement compared to before 👍  🥳 So yes, ready for release  🥳

**Comment by klues** [comment]
released with https://github.com/asterics/AsTeRICS-Grid/releases/tag/release-2026-02-27-09.38%2F%2B0100

yeah - thanks so much for all the testing and feedback! 👍 💯
